"""add document_chunks table with vector embedding

Revision ID: 07021a0d1433
Revises: 529eec2da014
Create Date: 2026-05-06 10:46:50.816323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  


# revision identifiers, used by Alembic.
revision: str = '07021a0d1433'
down_revision: Union[str, None] = '529eec2da014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('company_id', sa.UUID(), nullable=False))
    op.add_column('document_chunks', sa.Column('chunk_text', sa.Text(), nullable=False))
    op.add_column('document_chunks', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True))
    op.create_index(op.f('ix_document_chunks_company_id'), 'document_chunks', ['company_id'], unique=False)
    op.create_foreign_key(None, 'document_chunks', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_column('document_chunks', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_index(op.f('ix_document_chunks_company_id'), table_name='document_chunks')
    op.drop_column('document_chunks', 'embedding')
    op.drop_column('document_chunks', 'chunk_text')
    op.drop_column('document_chunks', 'company_id')
    # ### end Alembic commands ###